const books = [
  {
    bookName: "Beyond-the-Sunset",
    author: "Anna Jacobs",
    read: true,
    rate: "5/5",
    img: "./assest/Beyond-the-Sunset.webp",
    category: "Trending",
  },
  {
    bookName: "Chasing Profits",
    author: "Gregory Cross",
    read: false,
    rate: "4.8/5",
    img: "./assest/Chasing-Profits.webp",
    category: "Trending",
  },
  {
    bookName: "Echoes Of A Hidden Soul",
    author: "Echo Bodine",
    read: false,
    rate: "5/5",
    img: "./assest/Echoes-of-a-Hidden-Soul.webp",
    category: "Trending",
  },
  {
    bookName: "Elemental Flames",
    author: "Phaedra Weldon",
    read: false,
    rate: "4.5/5",
    img: "./assest/Elemental-Flames.webp",
    category: "Trending",
  },
  {
    bookName: "The Fire Within",
    author: "Chris d'Lacey",
    read: false,
    rate: "3.8/5",
    img: "./assest/The-Fire-Within.webp",
    category: "Popular",
  },
  {
    bookName: "The Perfect Proposal",
    author: "Katie Forde",
    read: false,
    rate: "3.8/5",
    img: "./assest/The-Perfect-Proposal.webp",
    category: "Popular",
  },
  {
    bookName: "Two Shadows",
    author: "Desiree Jury",
    read: false,
    rate: "4.1/5",
    img: "./assest/Two-Shadows.webp",
    category: "Popular",
  },
  {
    bookName: "Unlocking Potential",
    author: "Michael K. Simpson",
    read: false,
    rate: "4.1/5",
    img: "./assest/Unlocking-Potential.webp",
    category: "Popular",
  },
  {
    bookName: "Beyond-the-Sunset",
    author: "Anna Jacobs",
    read: true,
    rate: "5/5",
    img: "./assest/Beyond-the-Sunset.webp",
    category: "All",
  },
  {
    bookName: "Chasing Profits",
    author: "Gregory Cross",
    read: false,
    rate: "4.8/5",
    img: "./assest/Chasing-Profits.webp",
    category: "All",
  },
  {
    bookName: "Echoes Of A Hidden Soul",
    author: "Echo Bodine",
    read: false,
    rate: "5/5",
    img: "./assest/Echoes-of-a-Hidden-Soul.webp",
    category: "All",
  },
  {
    bookName: "Elemental Flames",
    author: "Phaedra Weldon",
    read: false,
    rate: "4.5/5",
    img: "./assest/Elemental-Flames.webp",
    category: "All",
  },
  {
    bookName: "The Fire Within",
    author: "Chris d'Lacey",
    read: false,
    rate: "3.8/5",
    img: "./assest/The-Fire-Within.webp",
    category: "All",
  },
  {
    bookName: "The Perfect Proposal",
    author: "Katie Forde",
    read: false,
    rate: "3.8/5",
    img: "./assest/The-Perfect-Proposal.webp",
    category: "All",
  },
  {
    bookName: "Two Shadows",
    author: "Desiree Jury",
    read: false,
    rate: "4.1/5",
    img: "./assest/Two-Shadows.webp",
    category: "All",
  },
  {
    bookName: "Unlocking Potential",
    author: "Michael K. Simpson",
    read: false,
    rate: "4.1/5",
    img: "./assest/Unlocking-Potential.webp",
    category: "All",
  },
  {
    bookName: "Fading Memories",
    author: "Ms. Joyce Smith",
    read: false,
    rate: "4.8/5",
    img: "./assest/Fading-Memories.webp",
    category: "All",
  },
  {
    bookName: "Flowing Hues",
    author: "J. M. Parramn",
    read: false,
    rate: "4.7/5",
    img: "./assest/Flowing-Hues.webp",
    category: "All",
  },
  {
    bookName: "Fractured Reality",
    author: "Rohit Trivedi",
    read: false,
    rate: "5/5",
    img: "./assest/Fractured-Reality-book-cover.webp",
    category: "All",
  },
  {
    bookName: "Hidden Wealth",
    author: "Gabriel Zucman",
    read: false,
    rate: "4.4/5",
    img: "./assest/Hidden-Wealth.webp",
    category: "All",
  },
  {
    bookName: "Launching Creativity",
    author: "Sarah Urist Green",
    read: false,
    rate: "4.2/5",
    img: "./assest/Launching-Creativity.webp",
    category: "All",
  },
  {
    bookName: "Legacy Of Prosperity",
    author: "Daisy J Dailzy",
    read: false,
    rate: "4.8/5",
    img: "./assest/Legacy-of-Prosperity.webp",
    category: "All",
  },
  {
    bookName: "Power Protein",
    author: "Mary Eades and Michael R Eades",
    read: false,
    rate: "4.4/5",
    img: "./assest/Power-Protein.webp",
    category: "All",
  },
  {
    bookName: "Protected By Love",
    author: "Carolyn Rae",
    read: false,
    rate: "3.5/5",
    img: "./assest/Protected-by-Love.webp",
    category: "All",
  },
  {
    bookName: "Sack Of Success",
    author: "Martin Amis",
    read: false,
    rate: "3.9/5",
    img: "./assest/Sack-of-Success.webp",
    category: "All",
  },
  {
    bookName: "The-Butterfly-Mind",
    author: "Victoria Williams",
    read: false,
    rate: "4.9/5",
    img: "./assest/The-Butterfly-Mind.webp",
    category: "All",
  },
];
